[package]
name = "host-leak-package"
version = "0.1.0"

[targets.cli]
kind = "exe"
main = "src/main.0"

[c.libs.hostonly]
headers = ["hostonly.h"]
include = ["/usr/include"]
lib = ["/usr/lib"]
link = ["hostonly"]
pkg_config = "hostonly"
